becours/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^', include('django.contrib.auth.urls', namespace='auth')),
    url(r'^', include('booking.urls', namespace='booking')),
    url(r'^admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

booking/urls.py
from django.conf.urls import url, include
from .views import HomeView, BookingListView, BookingDetailView, CreateAgreementView, OccupancyView, StatsView


urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^booking/$', BookingListView.as_view(), name='booking_list'),
    url(r'^booking/(?P<pk>\d+)/$', BookingDetailView.as_view(), name='booking_detail'),
    url(r'^booking/(?P<pk>\d+)/create_agreement/$', CreateAgreementView.as_view(), name='create_agreement'),
    url(r'^occupancy/$', OccupancyView.as_view()),
    url(r'^stats/$', StatsView.as_view()),
]

booking/models.py
from cuser.middleware import CuserMiddleware
from decimal import Decimal
from django.db import models
from django.db.models import Case, ExpressionWrapper, F, Min, Max, Sum, Value, When
from django.db.models.functions import Coalesce, ExtractDay
from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.urls import reverse
from django.utils.timezone import now
from math import floor


class TrackingEvent(models.Model):
    ADD = 1
    CHANGE = 2
    DELETE = 3
    OPERATION_CHOICES = (
        (ADD, "Ajout"),
        (CHANGE, "Modification"),
        (DELETE, "Suppression"),
    )
    operation = models.IntegerField(verbose_name="Opération", choices=OPERATION_CHOICES)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="Utilisateur", blank=True, null=True,
                             related_name="tracking_events", on_delete=models.PROTECT)
    date = models.DateTimeField()
    obj_ct = models.ForeignKey(ContentType, related_name='log_entries', on_delete=models.PROTECT)
    obj_pk = models.PositiveIntegerField()
    obj = GenericForeignKey('obj_ct', 'obj_pk')

    class Meta:
        verbose_name = "Événement"


class TrackingValue(models.Model):
    event = models.ForeignKey(TrackingEvent, verbose_name="Événement")
    field = models.CharField(max_length=100, verbose_name="Champ")
    value = models.TextField(null=True, verbose_name="Valeur")

    class Meta:
        verbose_name = "Valeur"


class TrackingMixin(object):
    def save(self, *args, **kwargs):
        change = bool(self.pk)
        if change:
            old = self.__class__.objects.get(pk=self.pk)
        super().save(*args, **kwargs)
        event = TrackingEvent.objects.create(
            operation=TrackingEvent.CHANGE if self.pk else TrackingEvent.ADD,
            user=CuserMiddleware.get_user(),
            date=now(),
            obj=self,
        )
        for field in self._meta.fields:
            if field.name == 'id':
                continue
            value = getattr(self, field.name)
            if not change and value is not None and value != "" or change and value != getattr(old, field.name):
                TrackingValue.objects.create(
                    event=event,
                    field=field.name,
                    value=str(value)
                )

    def delete(self, *args, **kwargs):
        TrackingEvent.objects.create(
            operation=TrackingEvent.DELETE,
            user=CuserMiddleware.get_user(),
            date=now(),
            obj=self,
        )
        super().delete(*args, **kwargs)


class Agreement(TrackingMixin, models.Model):
    date = models.DateField(verbose_name="Date")
    order = models.IntegerField(verbose_name="Numéro d'ordre")
    odt = models.FileField(upload_to='conventions', blank=True)
    pdf = models.FileField(upload_to='conventions', blank=True)
    booking = models.ForeignKey('Booking', verbose_name="Réservation", related_name='agreements', null=True)

    class Meta:
        verbose_name = "Convention"
        get_latest_by = 'date'

    def number(self):
        return "{year}-{order:03}".format(year=self.date.year, order=self.order)
    number.short_description = "Numéro"

    def __str__(self):
        return self.number()


class BookingState(TrackingMixin, models.Model):
    INCOME_CHOICES = (
        (1, "Potentiel"),
        (2, "Confirmé"),
        (3, "Facturé"),
        (4, "Infirmé"),
        (5, "Annulé"),
    )
    COLOR_CHOICES = (
        ('default', "Gris"),
        ('primary', "Bleu"),
        ('success', "Vert"),
        ('info', "Cyan"),
        ('warning', "Orange"),
        ('danger', "Rouge"),
    )
    title = models.CharField(verbose_name="Intitulé", max_length=100)
    income = models.IntegerField(verbose_name="Chiffre d'affaire", choices=INCOME_CHOICES)
    color = models.CharField(verbose_name="Couleur", max_length=10, choices=COLOR_CHOICES)

    class Meta:
        verbose_name = "Statut"
        ordering = ('title', )

    def __str__(self):
        return self.title


class BookingManager(models.Manager):
    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.annotate(begin=Min('items__begin'), end=Max('items__end'))
        qs = qs.annotate(nights=ExtractDay(F('end') - F('begin')))
        qs = qs.annotate(headcount=Sum('items__headcount'))
        overnights = ExtractDay(F('items__end') - F('items__begin')) * F('items__headcount')
        qs = qs.annotate(overnights=ExpressionWrapper(Sum(overnights), output_field=models.DecimalField()))
        qs = qs.annotate(price=Coalesce(Sum('items__price'), 0))
        amount_pppn = ExtractDay(F('items__end') - F('items__begin')) * F('items__headcount') * F('items__price_pppn')
        qs = qs.annotate(amount_pppn=ExpressionWrapper(Coalesce(Sum(amount_pppn), 0), output_field=models.DecimalField()))
        amount_pp = F('items__headcount') * F('items__price_pp')
        qs = qs.annotate(amount_pp=ExpressionWrapper(Coalesce(Sum(amount_pp), 0), output_field=models.DecimalField()))
        amount_pn = ExtractDay(F('items__end') - F('items__begin')) * F('items__price_pn')
        qs = qs.annotate(amount_pn=ExpressionWrapper(Coalesce(Sum(amount_pn), 0), output_field=models.DecimalField()))
        sub_amount_cot = ExpressionWrapper(ExtractDay(F('items__end') - F('items__begin')) * F('items__headcount'),
                                           output_field=models.DecimalField())
        amount_cot = Case(When(items__cotisation=True, then=sub_amount_cot))
        qs = qs.annotate(amount_cot=ExpressionWrapper(Coalesce(Sum(amount_cot), 0), output_field=models.DecimalField()))
        qs = qs.annotate(amount=F('price') + F('amount_pppn') + F('amount_pp') + F('amount_pn') + F('amount_cot'))
        qs = qs.annotate(deposit=F('amount') * .3)
        qs = qs.annotate(payment=Sum('payments__amount'))
        qs = qs.annotate(balance=F('amount') - F('payment'))
        return qs


class Booking(TrackingMixin, models.Model):
    ORG_TYPE_CHOICES = (
        (1, "EEDF"),
        (2, "Scouts français"),
        (3, "Scouts étrangers"),
        (4, "Association"),
        (5, "Particulier"),
        (6, "Scolaires"),
    )
    title = models.CharField(verbose_name="Intitulé", max_length=100, blank=True)
    org_type = models.IntegerField(verbose_name="Type d'organisation", choices=ORG_TYPE_CHOICES, blank=True, null=True)
    contact = models.CharField(verbose_name="Contact", max_length=100, blank=True)
    email = models.EmailField(verbose_name="Email", blank=True)
    tel = models.CharField(verbose_name="Téléphone", max_length=12, blank=True)
    state = models.ForeignKey(BookingState, verbose_name="Statut", blank=True, null=True)
    description = models.TextField(verbose_name="Description", blank=True)
    signed_agreement = models.OneToOneField(Agreement, verbose_name="N° convention signée", blank=True, null=True,
                                            related_name='signedx_booking')
    signed_agreement_scan = models.FileField(verbose_name="Scan convention signée", upload_to='conventions_signees',
                                             blank=True)

    objects = BookingManager()

    class Meta:
        verbose_name = "Réservation"

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('booking:booking_detail', kwargs={'pk': self.pk})

    @property
    def terrain(self):
        return self.items.filter(product=1).exists()

    @property
    def village(self):
        return self.items.filter(product=2).exists()

    @property
    def agreement(self):
        return self.agreements.latest()


class BookingItemManager(models.Manager):
    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.annotate(nights=ExtractDay(F('end') - F('begin')))
        qs = qs.annotate(overnights=ExpressionWrapper(F('nights') * F('headcount'), output_field=models.DecimalField()))
        amount_pppn = Coalesce(F('overnights') * F('price_pppn'), 0)
        qs = qs.annotate(amount_pppn=ExpressionWrapper(amount_pppn, output_field=models.DecimalField()))
        amount_pp = Coalesce(F('headcount') * F('price_pp'), 0)
        qs = qs.annotate(amount_pp=ExpressionWrapper(amount_pp, output_field=models.DecimalField()))
        amount_pn = Coalesce(F('nights') * F('price_pn'), 0)
        qs = qs.annotate(amount_pn=ExpressionWrapper(amount_pn, output_field=models.DecimalField()))
        amount_cot = Coalesce(Case(When(cotisation=True, then=F('overnights'))), 0)
        qs = qs.annotate(amount_cot=ExpressionWrapper(amount_cot, output_field=models.DecimalField()))
        qs = qs.annotate(amount=Coalesce(F('price'), 0) + F('amount_pppn') + F('amount_pp') + F('amount_pn') + F('amount_cot'))
        return qs


class BookingItem(TrackingMixin, models.Model):
    PRODUCT_CHOICES = (
        (1, "Hébergement Terrain"),
        (2, "Hébergement Hameau"),
        (3, "Location matériel"),
        (4, "Refacturation"),
        (5, "Salles"),
    )
    title = models.CharField(verbose_name="Intitulé", max_length=100, blank=True)
    booking = models.ForeignKey(Booking, related_name='items', on_delete=models.CASCADE)
    headcount = models.PositiveIntegerField(verbose_name="Effectif", blank=True, null=True)
    begin = models.DateField(verbose_name="Date de début", blank=True, null=True)
    end = models.DateField(verbose_name="Date de fin", blank=True, null=True)
    product = models.IntegerField(verbose_name="Produit", choices=PRODUCT_CHOICES)
    price_pppn = models.DecimalField(verbose_name="Prix/nuitée", max_digits=8, decimal_places=2, null=True, blank=True)
    price_pn = models.DecimalField(verbose_name="Prix/nuit", max_digits=8, decimal_places=2, null=True, blank=True)
    price_pp = models.DecimalField(verbose_name="Prix/pers", max_digits=8, decimal_places=2, null=True, blank=True)

booking/views.py
from datetime import date, timedelta
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.files import File
from django.db.models import Min, Sum
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils.text import slugify
from django.utils.timezone import now
from django.views.generic import ListView, TemplateView, DetailView
from os import unlink
from templated_docs import fill_template
from .models import Booking, BookingItem, Agreement


class HomeView(TemplateView):
    template_name = 'booking/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        potential_incomes = [item.amount - item.amount_cot for item in BookingItem.objects.filter(booking__state__income=1)]
        potential_overnights = [item.overnights for item in BookingItem.objects.filter(booking__state__income=1)]
        context['potential_income'] = sum(filter(bool, potential_incomes))
        context['potential_overnights'] = sum(filter(bool, potential_overnights))
        confirmed_incomes = [item.amount - item.amount_cot for item in BookingItem.objects.filter(booking__state__income__in=(2, 3))]
        confirmed_overnights = [item.overnights for item in BookingItem.objects.filter(booking__state__income__in=(2, 3))]
        context['confirmed_income'] = sum(filter(bool, confirmed_incomes))
        context['confirmed_overnights'] = sum(filter(bool, confirmed_overnights))
        context['total_income'] = context['potential_income'] + context['confirmed_income']
        context['total_overnights'] = context['potential_overnights'] + context['confirmed_overnights']
        return context


class BookingListView(ListView):
    queryset = Booking.objects.order_by('begin')


class BookingDetailView(DetailView):
    model = Booking


class CreateAgreementView(LoginRequiredMixin, DetailView):
    model = Booking

    def render_to_response(self, context, **response_kwargs):
        year = self.object.items.earliest('begin').begin.year
        try:
            order = Agreement.objects.filter(date__year=year).latest('order').order + 1
        except Agreement.DoesNotExist:
            order = 1
        agreement = Agreement.objects.create(date=now().date(), order=order, booking=self.object)
        context['agreement'] = agreement
        for ext in ('odt', 'pdf'):
            filename = fill_template('booking/agreement.odt', context, output_format=ext)
            visible_filename = "Convention_{number}_{title}.{ext}".format(number=agreement.number(), ext=ext,
                                                                          title=slugify(self.object.title))
            f = open(filename, 'rb')
            getattr(agreement, ext).save(visible_filename, File(f))
            f.close()
            unlink(filename)
        return HttpResponseRedirect(reverse('booking:booking_detail', kwargs={'pk': self.object.pk}))


class OccupancyView(TemplateView):
    template_name = 'booking/occupancy.html'

    def occupancy_for(self, day, product):
        items = BookingItem.objects.filter(begin__lte=day, end__gt=day, product=product)
        items = items.filter(booking__state__income__in=(1, 2, 3), headcount__isnull=False)
        items = items.order_by('booking__title')
        items = items.values('booking__title', 'booking__state__color')
        items = items.annotate(headcount=Sum('headcount'))
        return (sum([item['headcount'] for item in items]), items)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        occupancy = []
        for i in range(365):
            day = date(2017, 1, 1) + timedelta(days=i)
            occupancy.append((day, ) + self.occupancy_for(day, 2) + self.occupancy_for(day, 1))
        context['occupancy'] = occupancy
        return context


class StatsView(TemplateView):
    template_name = 'booking/stats.html'

    def get_context_data(self, **kwargs):
        items = BookingItem.objects.all()
        kwargs['stats'] = {
            'headcount': sum([item.headcount for item in items if item.headcount]),
            'overnights': sum([item.overnights for item in items if item.overnights]),
            'amount_hosting': sum([item.amount - item.amount_cot for item in items if item.product in (1, 2, 5)]),
            'amount_cot': sum([item.overnights for item in items if item.overnights]),
            'amount_other': sum([item.amount for item in items if item.product in (3, 4)]),
            'amount': sum([item.amount for item in items]),
        }
        kwargs['stats']['overnight_cost'] = kwargs['stats']['amount_hosting'] / kwargs['stats']['overnights']

        STATS = (
            ('stats_eedf', BookingItem.objects.filter(booking__org_type=1)),
            ('stats_ext', BookingItem.objects.exclude(booking__org_type=1)),
            ('stats_village', BookingItem.objects.filter(product__in=(2, 5))),
            ('stats_terrain', BookingItem.objects.filter(product=1)),
            ('stats_village_eedf', BookingItem.objects.filter(booking__org_type=1, product__in=(2, 5))),
            ('stats_village_ext', BookingItem.objects.exclude(booking__org_type=1).filter(product__in=(2, 5))),
            ('stats_terrain_eedf', BookingItem.objects.filter(booking__org_type=1, product=1)),
            ('stats_terrain_ext', BookingItem.objects.exclude(booking__org_type=1).filter(product=1)),
            ('stats_ete', BookingItem.objects.filter(end__gte='2017-07-01', begin__lte='2017-08-31')),
            ('stats_avr', BookingItem.objects.filter(end__gte='2017-04-16', begin__lte='2017-05-01')),
            ('stats_oct', BookingItem.objects.filter(end__gte='2017-10-20', begin__lte='2017-11-02')),
        )
        for (name, items) in STATS:
            kwargs[name] = {
                'headcount': sum([item.headcount for item in items if item.headcount]),
                'overnights': sum([item.overnights for item in items if item.overnights]),
                'amount_hosting': sum([item.amount - item.amount_cot for item in items if item.product in (1, 2, 5)]),
                'amount_cot': sum([item.overnights for item in items if item.overnights]),
                'amount_other': sum([item.amount for item in items if item.product in (3, 4)]),
                'amount': sum([item.amount for item in items]),
            }
            kwargs[name]['overnights_rate'] = (100 * kwargs[name]['overnights'] / kwargs['stats']['overnights'])
            kwargs[name]['amount_hosting_rate'] = (100 * kwargs[name]['amount_hosting'] / kwargs['stats']['amount_hosting'])
            kwargs[name]['overnight_cost'] = kwargs[name]['overnights'] and kwargs[name]['amount_hosting'] / kwargs[name]['overnights']


        return kwargs

booking/templates/booking/booking_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container">

    <h1>{{ booking.title }}</h1>

    <table class="table table-striped table-hover table-condensed">
        <tr>
            <th>Statut</th>
            <td><span class="label label-{{ booking.state.color }}">{{ booking.state.title }}</span></td>
            <td></td>
        </tr>
        <tr>
            <th>Contact</th>
            <td><a href="mailto:{{ booking.email }}">{{ booking.contact }}</a></td>
            <td></td>
        </tr>
        <tr>
            <th>Tel</th>
            <td>{{ booking.tel }}</td>
            <td></td>
        </tr>
        <tr>
            <th>Dates</th>
            <td>Du {{ booking.begin|date:'D d/m/y' }} au {{ booking.end|date:'D d/m/y' }}</td>
            <td></td>
        </tr>
        <tr>
            <th>Nuits</th>
            <td>{{ booking.nights|default_if_none:"" }}</td>
            <td></td>
        </tr>
        <tr>
            <th>Effectif</th>
            <td>{{ booking.headcount|default_if_none:"" }}</td>
            <td></td>
        </tr>
        <tr>
            <th>Nuitées</th>
            <td>{{ booking.overnights|default_if_none:"" }}</td>
            <td></td>
        </tr>
        {% for item in booking.items.all %}
            {% if item.price_pppn is not None %}
                <tr>
                    <th>{% if item.intitule %}{{ item.intitule }}{% else %}{{ item.get_product_display }}{% endif %}</th>
                    <td>{{ item.price_pppn|floatformat:2 }} € x {{ item.headcount }} pers. x {{ item.nights }} nuits
                        (du {{ item.begin|date:'D d/m/y' }} au {{ item.end|date:'D d/m/y' }})</td>
                    <td class="text-right">{{ item.amount_pppn|floatformat:2 }} €</td>
                </tr>
            {% endif %}
            {% if item.price_pp is not None %}
                <tr>
                    <th>{% if item.intitule %}{{ item.intitule }}{% else %}{{ item.get_product_display }}{% endif %}</th>
                    <td>{{ item.price_pp|floatformat:2 }} € x {{ item.headcount }} pers.</td>
                    <td class="text-right">{{ item.amount_pp|floatformat:2 }} €</td>
                </tr>
            {% endif %}
            {% if item.price_pn is not None %}
                <tr>
                    <th>{% if item.intitule %}{{ item.intitule }}{% else %}{{ item.get_product_display }}{% endif %}</th>
                    <td>{{ item.price_pn|floatformat:2 }} € x {{ item.nights }} nuits
                        (du {{ item.begin|date:'D d/m/y' }} au {{ item.end|date:'D d/m/y' }})</td>
                    <td class="text-right">{{ item.amount_pn|floatformat:2 }} €</td>
                </tr>
            {% endif %}
            {% if item.price is not None %}
                <tr>
                    <th>{% if item.intitule %}{{ item.intitule }}{% else %}{{ item.get_product_display }}{% endif %}</th>
                    <td>forfait</td>
                    <td class="text-right">{{ item.price|floatformat:2 }} €</td>
                </tr>
            {% endif %}
            {% if item.cotisation %}
                <tr>
                    <th>Cotisation EEDF membre associé</th>
                    <td>1,00 € x {{ item.headcount }} pers. x {{ item.nights }} nuits
                        (du {{ item.begin|date:'D d/m/y' }} au {{ item.end|date:'D d/m/y' }})</td>
                    <td class="text-right">{{ item.amount_cot|floatformat:2 }} €</td>
                </tr>
            {% endif %}
        {% endfor %}
        <tr>
            <th>Montant total</th>
            <td></td>
            <td class="text-right">{% if booking.amount %}{{ booking.amount|floatformat:2 }} €{% endif %}</td>
        </tr>
        <tr>
            <th>Arrhes</th>
            <td></td>
            <td class="text-right">{% if booking.deposit %}{{ booking.deposit|floatformat:2 }} €{%  endif %}</td>
        </tr>
        <tr>
            <th>Paiement</th>
            <td></td>
            <td class="text-right">{% if booking.payment %}{{ booking.payment|floatformat:2 }} €{%  endif %}</td>
        </tr>
        <tr>
            <th>Solde</th>
            <td></td>
            <td class="text-right">{% if booking.balance %}{{ booking.balance|floatformat:2 }} €{%  endif %}</td>
        </tr>
        {% for agreement in booking.agreements.all %}
            <tr>
                <th>Convention</th>
                <td>
                    {% if agreement.pdf %}<a href="{{ agreement.pdf.url }}">{{ agreement.number }}</a>{% endif %}
                    {% if agreement.odt %}(<a href="{{ agreement.odt.url }}">éditer</a>){% endif %}
                </td>
                <td></td>
            </tr>
        {% empty %}
            <tr>
                <th>Convention</th>
                <td>
                    <a href="{% url 'booking:create_agreement' booking.id %}" class="btn btn-xs btn-primary">
                        <span class="glyphicon glyphicon-file"></span>
                        Créer
                    </a>
                <td></td>
            </tr>
        {% endfor %}
        {% if booking.signed_agreement or booking.signed_agreement_scan %}
            <tr>
                <th>Convention signée</th>
                <td>
                    {% if booking.signed_agreement_scan %}<a href="{{ booking.signed_agreement_scan.url }}">{% endif %}
                    {{ booking.signed_agreement.number }}
                    {% if booking.signed_agreement_scan %}</a>{% endif %}
                </td>
                <td></td>
            </tr>
    {%  endif %}
    </table>

</div>

{% endblock content %}

booking/templates/booking/booking_list.html
{% extends 'base.html' %}

{% block content %}

<div class="container-fluid">

    <h1>Réservations</h1>

    <table class="table table-striped table-hover">
        <tr>
            <th>Intitulé</th>
            <th>Statut</th>
            <th>Contact</th>
            <th>Tel</th>
            <th>Du</th>
            <th>Au</th>
            <th>Nuits</th>
            <th>Effectif</th>
            <th>Nuitées</th>
            <th>Montant</th>
            <th>Arrhes</th>
            <th>Paiement</th>
            <th>Solde</th>
            <th>Convention</th>
        </tr>
        {% for booking in booking_list %}
            <tr>
                <td><a href="{{ booking.get_absolute_url }}">{{ booking.title }}</a></td>
                <td><span class="label label-{{ booking.state.color }}">{{ booking.state.title }}</span></td>
                <td><a href="mailto:{{ booking.email }}">{{ booking.contact }}</a></td>
                <td>{{ booking.tel }}</td>
                <td align="right">{{ booking.begin|date:'D d/m/y' }}</td>
                <td align="right">{{ booking.end|date:'D d/m/y' }}</td>
                <td align="right">{{ booking.nights|default_if_none:"" }}</td>
                <td align="right">{{ booking.headcount|default_if_none:"" }}</td>
                <td align="right">{{ booking.overnights|default_if_none:"" }}</td>
                <td align="right">{% if booking.amount %}{{ booking.amount|floatformat:2 }} €{% endif %}</td>
                <td align="right">{% if booking.deposit %}{{ booking.deposit|floatformat:2 }} €{%  endif %}</td>
                <td align="right">{% if booking.payment %}{{ booking.payment|floatformat:2 }} €{%  endif %}</td>
                <td align="right">{% if booking.balance %}{{ booking.balance|floatformat:2 }} €{%  endif %}</td>
                <td>
                    {%  if booking.agreement and booking.agreement.pdf %}
                        <a href="{{ booking.agreement.pdf.url }}">{{ booking.agreement.number }}</a>
                    {% else %}{% comment %}
                        <a href="{% url 'booking:create_agreement' booking.id %}" class="btn btn-xs btn-primary">
                            <span class="glyphicon glyphicon-file"></span>
                            Créer
                        </a>{%endcomment %}
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </table>

</div>

{% endblock content %}

booking/templates/booking/home.html
{% extends 'base.html' %}

{% block content %}

    <div class="container income">
        <div class="row">
            <div class="col-md-2">CA potential</div>
            <div class="col-md-2 text-right"><span class="label label-warning">{{ potential_income|floatformat:2 }} €</span></div>
            <div class="col-md-2 text-right"><span class="label label-warning">{{ potential_overnights|floatformat }} nuitées</span></div>
        </div>
        <div class="row">
            <div class="col-md-2">CA confirmé/facturé</div>
            <div class="col-md-2 text-right"><span class="label label-primary">{{ confirmed_income|floatformat:2 }} €</span></div>
            <div class="col-md-2 text-right"><span class="label label-primary">{{ confirmed_overnights|floatformat }} nuitées</span></div>
        </div>
        <div class="row">
            <div class="col-md-2">CA total</div>
            <div class="col-md-2 text-right"><span class="label label-default">{{ total_income|floatformat:2 }} €</span></div>
            <div class="col-md-2 text-right"><span class="label label-default">{{ total_overnights|floatformat }} nuitées</span></div>
        </div>
    </div>

{% endblock content %}

booking/templates/booking/occupancy.html
{% extends 'base.html' %}

{% block content %}

<div class="container-fluid">

    <h1>Occupation du terrain</h1>

    <table class="table table-striped table-hover table-condensed">
        <tr>
            <th>Jour</th>
            <th></th>
            <th>Mois</th>
            <th>Hameau</th>
            <th></th>
            <th>Terrain</th>
            <th></th>
        </tr>
        {% for day, headcount1, items1, headcount2, items2 in occupancy %}
            {% if headcount1 or headcount2 %}
                <tr>
                    <td>{{ day|date:'l' }}</td>
                    <td>{{ day|date:'d' }}</td>
                    <td>{{ day|date:'F' }}</td>
                    <td><span class="badge">{{ headcount1|default:"" }}</span></td>
                    <td>
                        {% for item in items1 %}
                            <span class="label label-{{ item.booking__state__color }}">{{ item.headcount }}</span>
                            {{ item.booking__title }}
                            {% if not forloop.last %} + {%endif %}
                        {% endfor %}
                    </td>
                    <td><span class="badge">{{ headcount2|default:"" }}</span></td>
                    <td>
                        {% for item in items2 %}
                            <span class="label label-{{ item.booking__state__color }}">{{ item.headcount }}</span>
                            {{ item.booking__title }}
                            {% if not forloop.last %} + {%endif %}
                        {% endfor %}
                    </td>
                </tr>
            {% endif %}
        {% endfor %}
    </table>

</div>

{% endblock content %}